[package]
name = "neolink"
description = "A standards-compliant bridge to Reolink IP cameras"
version = "0.6.3-rc.3"
authors = ["George Hilliard <thirtythreeforty@gmail.com>", "Andrew King <sheepchaan@gmail.com>"]
edition = "2018"
license = "AGPL-3.0-or-later"

[workspace]
members = [
  "crates/*",
]

[dependencies]
anyhow = "1.0"
base64 = "0.22"
byte-slice-cast = {version = "1.2", optional = true}
bytes = "1.6"
clap = { version = "4.5", features = ["derive", "cargo"] }
crossbeam-channel = {version = "0.5", optional = true}
dirs = {version = "5.0", optional = true}
env_logger = "0.11"
fcm-push-listener = {version = "2.0", optional = true}
futures = "0.3"
gstreamer = {version = "0.23", optional = true}
gstreamer-app = { version = "0.23", features = ["v1_20"], optional = true }
gstreamer-rtsp = { version = "0.23", features = ["v1_20"], optional = true }
gstreamer-rtsp-server = { version = "0.23", features = ["v1_20"], optional = true }
heck = "0.5"
log = { version = "0.4", features = [ "release_max_level_debug" ] }
md5 = {version = "0.7", optional = true}
neolink_core = { path = "crates/core", version = "0.6.3-rc.3" }
once_cell = "1.19"
quick-xml = { version = "0.36", features = ["serialize"] }
regex = "1.10"
rumqttc = "0.24"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tokio = { version = "1.37", features = ["rt-multi-thread", "macros", "io-util", "tracing"] }
tokio-stream = "0.1"
tokio-util = { version = "0.7", features = ["full", "tracing"] }
toml = "0.8"
uuid = { version = "1.8", features = ["v4"] }
validator = {version="0.18", features = ["derive"] }

[target.'cfg(not(target_env = "msvc"))'.dependencies]
tikv-jemallocator = "0.5"

[features]
default = ["gstreamer"]
gstreamer = [
  "dep:gstreamer",
  "dep:gstreamer-app",
  "dep:gstreamer-rtsp",
  "dep:gstreamer-rtsp-server",
  "dep:byte-slice-cast",
  "dep:crossbeam-channel"
]
pushnoti = [
  "dep:fcm-push-listener",
  "dep:dirs",
  "dep:md5"
]
